version: 2
test:
  working_directory: ~/my-app
  docker:
    - image: cimg/node:14.16.0
  steps:
    - checkout

    - run:
        name: Installing dependencies
        command: npm ci

    - run:
        name: Run tests
        command: npm run test -- --coverage --watchAll=false

    - run:
        name: Upload code coverage
        command: bash <(curl -s https://codecov.io/bash) -t $CODECOV_TOKEN

workflows:
  test-coverage:
    jobs:
      - test